# Generated by Django 4.2.6 on 2024-01-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fueldrawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyfuel',
            name='Tasks',
            field=models.CharField(choices=[('Energy Reading and Diesel Filling', 'Energy Reading and Diesel Filling'), ('Energy Reading', 'Energy Reading')], max_length=50, verbose_name='Tasks'),
        ),
    ]
